### ISSUE TITLE
Som en spiller så vil jeg kunne spille spilllet med andre spillere [Multiplayer]

### ISSUE THREAD

**Issue by mrtineide** [inf112-v21/Runtime-Terror-Import-Team_Name-Error-404-Team-Name-Not-Found#29]
Som en spiller så vil jeg kunne spille spilllet med andre spillere
- Akseptansekriterier:   
    - [ ]  Som spiller må jeg kunne see de andre spillerene på spillet for å planlegge
    - [x]  Som en Host må jeg kunne la klienter "joine" meg slik at vi kan spille sammen
    - [ ]  Som host må jeg kunne få informasjonen til klienten slik at spillet kan opptateres

- Arbeidsoppgave:
    - [x]  lage en host som kan snakke med klienter
    - [x]  lage en host som klienter kan koble seg til
    - [ ]  kunne styre alle komandoene fra klienten slik at brikkene på brettet beveger seg
    - [ ]  klienten må kunne sende ordre til hosten
